config/routes.rb
Rails.application.routes.draw do
  root :to => 'beautiful#dashboard'
  match ':model_sym/select_fields' => 'beautiful#select_fields', :via => [:get, :post]

  concern :bs_routes do
    collection do
      post :batch
      get  :treeview, :my_index
      match :search_and_filter, :action => :index, :as => :search, :via => [:get, :post]
    end
    member do
      post :treeview_update
    end
  end
  authenticate :user do
    resources :evaluations, only: [:new, :create, :edit, :update, :my_index]
    resources :places, only: [:new, :create, :edit, :update]
  end
  # Add route with concerns: :bs_routes here # Do not remove
  resources :places, concerns: :bs_routes
  
  resources :evaluations, concerns: :bs_routes
  

  resources :static_pages
  devise_for :users, :evaluations

  root to: "application#index"

  get '/about', to: 'static_pages#about'
#  get '/my_index', to: 'evaluations#my_index'
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :user
  belongs_to :place

  validates :place_id, presence: true

  validates :internet,:service,:price,:accomodation,:noyse,:general, presence: true, numericality: { greater_than: 0,  lesser_than: 6}

  include DefaultSortingConcern
  include FulltextConcern
  include CaptionConcern

  cattr_accessor :fulltext_fields do
    []
  end

  def self.permitted_attributes
    return :internet,:food,:drink,:service,:price,:accomodation,:noyse,:general,:user_id, :place_id
  end
end

app/controllers/evaluations_controller.rb
# encoding : utf-8


class EvaluationsController < BeautifulController

  before_action :load_evaluation, :only => [:show, :edit, :update]
  # Uncomment for check abilities with CanCan
  #authorize_resource

  def index
    session['fields'] ||= {}
    session['fields']['evaluation'] ||= (Evaluation.columns.map(&:name) - ["id"])[0..4]
    do_select_fields('evaluation')
    do_sort_and_paginate('evaluation')
    
    @q = Evaluation.ransack(
      params[:q]
    )

    @evaluation_scope = @q.result(
      :distinct => true
    ).sorting(
      params[:sorting]
    ).includes(:place)
    
    @evaluation_scope_for_scope = @evaluation_scope.dup
    
    unless params[:scope].blank?
      @evaluation_scope = @evaluation_scope.send(params[:scope])
    end
    
    @evaluations = @evaluation_scope.paginate(
      :page => params[:page],
      :per_page => 20
    ).to_a

    respond_to do |format|
      format.html{
        render
      }
      format.json{
        render :json => @evaluation_scope.to_a
      }
      format.csv{
        require 'csv'
        csvstr = CSV.generate do |csv|
          csv << Evaluation.attribute_names
          @evaluation_scope.to_a.each{ |o|
            csv << Evaluation.attribute_names.map{ |a| o[a] }
          }
        end 
        render :text => csvstr
      }
      format.xml{ 
        render :xml => @evaluation_scope.to_a
      }             
      format.pdf{
        pdfcontent = PdfReport.new.to_pdf(Evaluation,@evaluation_scope)
        send_data pdfcontent
      }
    end
  end

  def my_index
    session['fields'] ||= {}
    session['fields']['evaluation'] ||= (Evaluation.columns.map(&:name) - ["id"])[0..4]
    do_select_fields('evaluation')
    do_sort_and_paginate('evaluation')
    
    @q = Evaluation.where(user_id: current_user.id).ransack(
      params[:q]
    )

    @evaluation_scope = @q.result(
      :distinct => true
    ).sorting(
      params[:sorting]
    )
    
    @evaluation_scope_for_scope = @evaluation_scope.dup
    
    unless params[:scope].blank?
      @evaluation_scope = @evaluation_scope.send(params[:scope])
    end
    
    @evaluations = @evaluation_scope.paginate(
      :page => params[:page],
      :per_page => 20
    ).to_a

    respond_to do |format|
      format.html{
        render
      }
      format.json{
        render :json => @evaluation_scope.to_a
      }
      format.csv{
        require 'csv'
        csvstr = CSV.generate do |csv|
          csv << Evaluation.attribute_names
          @evaluation_scope.to_a.each{ |o|
            csv << Evaluation.attribute_names.map{ |a| o[a] }
          }
        end 
        render :text => csvstr
      }
      format.xml{ 
        render :xml => @evaluation_scope.to_a
      }             
      format.pdf{
        pdfcontent = PdfReport.new.to_pdf(Evaluation,@evaluation_scope)
        send_data pdfcontent
      }
    end
  end

  def show
    respond_to do |format|
      format.html{
        render
      }
      format.json { render :json => @evaluation }
    end
  end

  def new
    @places = Place.all.select(:id, :name)
    puts "Oee"
    puts @places
    @evaluation = Evaluation.new

    respond_to do |format|
      format.html{
        render
      }
      format.json { render :json => @evaluation }
    end
  end

  def edit
    @places = Place.all.select(:id, :name)
    
  end

  def create
    @places = Place.all.select(:id, :name)
    @evaluation = Evaluation.new(params_for_model)
    @evaluation.user = current_user

    respond_to do |format|
      if @evaluation.save
        format.html {
          if params[:mass_inserting] then
            redirect_to evaluations_path(:mass_inserting => true)
          else
            redirect_to evaluation_path(@evaluation), :flash => { :notice => t(:create_success, :model => "evaluation") }
          end
        }
        format.json { render :json => @evaluation, :status => :created, :location => @evaluation }
      else
        format.html {
          if params[:mass_inserting] then
            redirect_to evaluations_path(:mass_inserting => true), :flash => { :error => t(:error, "Error") }
          else
            render :action => "new"
          end
        }
        format.json { render :json => @evaluation.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @evaluation.update_attributes(params_for_model) and current_user.id == @evaluation.user.id
        format.html { redirect_to evaluation_path(@evaluation), :flash => { :notice => t(:update_success, :model => "evaluation") }}
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @evaluation.errors, :status => :unprocessable_entity }
      end
    end
  end

# def destroy
#   @evaluation.destroy

#   respond_to do |format|
#     format.html { redirect_to evaluations_url }
#     format.json { head :ok }
#   end
# end

  def batch
    attr_or_method, value = params[:actionprocess].split(".")

    @evaluations = []    
    
    Evaluation.transaction do
      if params[:checkallelt] == "all" then
        # Selected with filter and search
        do_sort_and_paginate(:evaluation)

        @evaluations = Evaluation.ransack(
          params[:q]
        ).result(
          :distinct => true
        )
      else
        # Selected elements
        @evaluations = Evaluation.find(params[:ids].to_a)
      end

      @evaluations.each{ |evaluation|
        if not Evaluation.columns_hash[attr_or_method].nil? and
               Evaluation.columns_hash[attr_or_method].type == :boolean then
         evaluation.update_attribute(attr_or_method, boolean(value))
         evaluation.save
        else
          case attr_or_method
          # Set here your own batch processing
          # evaluation.save
          when "destroy" then
            evaluation.destroy
          end
        end
      }
    end
    
    redirect_to :back
  end

  def treeview

  end

  def treeview_update
    modelclass = Evaluation
    foreignkey = :evaluation_id

    render :nothing => true, :status => (update_treeview(modelclass, foreignkey) ? 200 : 500)
  end
  
  private 
  
  def load_evaluation
    @evaluation = Evaluation.find(params[:id])
  end

  def params_for_model
    params.require(:evaluation).permit(Evaluation.permitted_attributes)
  end
end

app/helpers/evaluations_helper.rb
# encoding : utf-8
require "beautiful_helper"


module EvaluationsHelper
end

app/views/evaluations/edit.html.erb
<h2><%= t(:editing, :default => 'Editing') %> <%= t('app.models.evaluation.bs_caption', :default => 'evaluation') %></h2>

<%= render 'form' %>

<%= link_to t(:back, :default => "Back"), evaluations_path, :class => "btn btn-default" %>

app/views/evaluations/index.html.erb
<h2><%= t(:listing, :default => "Listing") %> <%= t('app.models.evaluation.bs_caption_plural', :default => 'evaluation') %></h2>

<p>
  <%= link_to '<i class="fa fa-plus"></i> '.html_safe + t(:new, :default => "New") + ' ' + t('app.models.evaluation.bs_caption', :default => 'evaluation'), new_evaluation_path, :class => "btn btn-default" %>
  <% if Evaluation.columns.map(&:name).include?("evaluation_id") then %>
    <%= link_to '<i class="fa fa-folder-close"></i> '.html_safe + t(:treeview, :default => "Treeview") + ' ' + t('app.models.evaluation.bs_caption', :default => 'evaluation'), treeview_evaluations_path, :class => "btn btn-default" %>
  <% end %>
</p>


<%# Set your scopes below (string in array) %>
<% scopes = [] %>
<% if not scopes.blank? then %>
<div class="btn-toolbar">
  <div class="btn-group">
    <%= link_to "All (#{@evaluation_scope_for_scope.count})", evaluations_path(:scope => ""), :class => "btn btn-default #{((session[:scope][:evaluation].to_s == '') ? 'active' : '')}" %>
    <% for scope in scopes %>
    <%= link_to "#{scope} (#{@evaluation_scope_for_scope.send(scope).count})", evaluations_path(:scope => scope), :class => "btn btn-default #{((session[:scope][:evaluation].to_s == scope) ? 'active' : '')}" %>
    <% end %>
  </div>
</div>
<% end %>

<div class="row">
  <div class="col-md-12">
    <a class="btn btn-xs btn-default" id="hide-menu-btn">
      <i class="fa fa-caret-left"></i>
      <i class="fa fa-caret-left"></i>
    </a>
    <a class="btn btn-xs btn-default" id="show-menu-btn">
      <i class="fa fa-caret-right"></i>
      <i class="fa fa-caret-right"></i>
    </a>

    <a class="btn btn-xs btn-default pull-right" id="hide-search-btn">
      <i class="fa fa-caret-right"></i>
      <i class="fa fa-caret-right"></i>
    </a>
    <a class="btn btn-xs btn-default pull-right" id="show-search-btn">
      <i class="fa fa-caret-left"></i>
      <i class="fa fa-caret-left"></i>
    </a>
  </div>
</div>

<div class="row">
  <div class="col-md-9">
    <%= form_tag  batch_evaluations_path, :class => "form-inline" do %>

      <%= render :partial => "layouts/modal_columns", :locals => { :engine_name => '', :model_name => "evaluation", :model_columns => ['place_id','internet','food','drink','service','price','accomodation','noyse','general','created_at','updated_at'] } %>

      <table class="table table-striped table-bordered table-condensed">
        <thead>
          <tr>
            <th class="ac">
              <a class="" data-toggle="modal" href="#modal-columns" title="<%= t(:select_columns, :default => "Select Columns") %>" ><i class="fa fa-th-list"></i></a>
            </th>
            <th>
              <%= check_box_tag :checkall, '' %>
            </th>
            <th  class="bs-col-place" >
              <%= sorting_header("evaluation", "place_id", "") %>
            </th>
            <th <%= visible_column("evaluation", "internet") %> class="bs-col-internet">
              <%= sorting_header("evaluation", "internet", "") %>
            </th>
            <th <%= visible_column("evaluation", "food") %> class="bs-col-food">
              <%= sorting_header("evaluation", "food", "") %>
            </th>
            <th <%= visible_column("evaluation", "drink") %> class="bs-col-drink">
              <%= sorting_header("evaluation", "drink", "") %>
            </th>
            <th <%= visible_column("evaluation", "service") %> class="bs-col-service">
              <%= sorting_header("evaluation", "service", "") %>
            </th>
            <th <%= visible_column("evaluation", "price") %> class="bs-col-price">
              <%= sorting_header("evaluation", "price", "") %>
            </th>
            <th <%= visible_column("evaluation", "accomodation") %> class="bs-col-accomodation">
              <%= sorting_header("evaluation", "accomodation", "") %>
            </th>
            <th <%= visible_column("evaluation", "noyse") %> class="bs-col-noyse">
              <%= sorting_header("evaluation", "noyse", "") %>
            </th>
            <th <%= visible_column("evaluation", "general") %> class="bs-col-general">
              <%= sorting_header("evaluation", "general", "") %>
            </th>

            <!-- Beautiful_scaffold - AddField - Header - Do not remove -->
            <th <%= visible_column("evaluation", "created_at") %> class="bs-col-created_at">
              <%= sorting_header("evaluation", "created_at", "") %>
            </th>
            <th <%= visible_column("evaluation", "updated_at") %> class="bs-col-updated_at">
              <%= sorting_header("evaluation", "updated_at", "") %>
            </th>
            <th colspan="3">
              <label class="checkbox">
                <%= check_box_tag :checkallelt, 'all' %>
                <%= pluralize(@evaluation_scope.count, t('app.models.evaluation.bs_caption', :default => 'evaluation'), t('app.models.evaluation.bs_caption_plural', :default => 'evaluation')) %>
              </label>
            </th>
          </tr>
        </thead>
        <tbody>
          <% @evaluations.each do |evaluation| %>
          <tr class="line-<%= cycle("1","2") %>">
            <td class="ar"><%= evaluation.id %></td>
            <td><%= check_box_tag "ids[]",evaluation.id, false, :class => 'cbbatch' %></td>
            <td   class="bs-col-place <%= align_attribute("string") %>">
                <%= Place.find(evaluation.place_id).name %>
            </td>
            <td <%= visible_column("evaluation", "internet") %> class="bs-col-internet <%= align_attribute("integer") %>">
                <%= evaluation.internet %>
            </td>
            <td <%= visible_column("evaluation", "food") %> class="bs-col-food <%= align_attribute("string") %>">
                <%= evaluation.food %>
            </td>
            <td <%= visible_column("evaluation", "drink") %> class="bs-col-drink <%= align_attribute("string") %>">
                <%= evaluation.drink %>
            </td>
            <td <%= visible_column("evaluation", "service") %> class="bs-col-service <%= align_attribute("integer") %>">
                <%= evaluation.service %>
            </td>
            <td <%= visible_column("evaluation", "price") %> class="bs-col-price <%= align_attribute("integer") %>">
                <%= evaluation.price %>
            </td>
            <td <%= visible_column("evaluation", "accomodation") %> class="bs-col-accomodation <%= align_attribute("integer") %>">
                <%= evaluation.accomodation %>
            </td>
            <td <%= visible_column("evaluation", "noyse") %> class="bs-col-noyse <%= align_attribute("integer") %>">
                <%= evaluation.noyse %>
            </td>
            <td <%= visible_column("evaluation", "general") %> class="bs-col-general <%= align_attribute("integer") %>">
                <%= evaluation.general %>
            </td>
<!-- Beautiful_scaffold - AddField - Column - Do not remove -->
            <td <%= visible_column("evaluation", "created_at") %> class="bs-col-created_at <%= align_attribute("datetime") %>">
              <%= l(evaluation.created_at, :format => :long) %>
            </td>
            <td <%= visible_column("evaluation", "updated_at") %> class="bs-col-updated_at <%= align_attribute("datetime") %>">
              <%= l(evaluation.updated_at, :format => :long) %>
            </td>
            <td class="ac am"><%= link_to '<i class="fa fa-search"></i>'.html_safe, evaluation_path(evaluation), :title => t(:show, :default => "Show") %></td>
            <td class="ac am"><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_evaluation_path(evaluation), :title => t(:edit, :default => "Edit") %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <div class="btn-toolbar">
        <div class="btn-group">
          <% clean_params %>
          <%= will_paginate @evaluations,
                  :inner_window => 0,
                  :outer_window => 0,
                  :previous_label => t(:prev, :default => "Previous"),
                  :next_label => t(:next, :default => "Next") %>

        </div>
        <div class="btn-group pull-right">
          <%= link_to '<i class="fa fa-download"></i> CSV'.html_safe,  evaluations_path(:format => :csv), :class => "btn btn-default" %>
          <%= link_to '<i class="fa fa-download"></i> XML'.html_safe,  evaluations_path(:format => :xml), :class => "btn btn-default" %>
          <%= link_to '<i class="fa fa-download"></i> JSON'.html_safe, evaluations_path(:format => :json), :class => "btn btn-default" %>
          <%= link_to '<i class="fa fa-download"></i> PDF'.html_safe,  evaluations_path(:format => :pdf), :class => "btn btn-default" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
    <%= search_form_for @q, :url => search_evaluations_path, :html => { :class => "well well-small search-and-filter" }, :method => :post do |f| %>

      <h3><%= t("search_and_filter", :default => "Search & filter") %></h3>

      <%= ransack_field("evaluation", "place_id", f, "Place") %>


      <!-- Beautiful_scaffold - AddField - Search - Do not remove -->



      <%= f.submit t(:filter, :default => "Filter"), :class => "btn btn-primary" %>
      <%= link_to  t(:cancel, :default => "Cancel"), evaluations_path(:nosearch => "ok"), :class => "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/evaluations/my_index.html.erb
<h2> My Evaluations  </h2>

<p>
  <%= link_to '<i class="fa fa-plus"></i> '.html_safe + t(:new, :default => "New") + ' ' + t('app.models.evaluation.bs_caption', :default => 'evaluation'), new_evaluation_path, :class => "btn btn-default" %>
  <% if Evaluation.columns.map(&:name).include?("evaluation_id") then %>
    <%= link_to '<i class="fa fa-folder-close"></i> '.html_safe + t(:treeview, :default => "Treeview") + ' ' + t('app.models.evaluation.bs_caption', :default => 'evaluation'), treeview_evaluations_path, :class => "btn btn-default" %>
  <% end %>
</p>


<%# Set your scopes below (string in array) %>
<% scopes = [] %>
<% if not scopes.blank? then %>
<div class="btn-toolbar">
  <div class="btn-group">
    <%= link_to "All (#{@evaluation_scope_for_scope.count})", evaluations_path(:scope => ""), :class => "btn btn-default #{((session[:scope][:evaluation].to_s == '') ? 'active' : '')}" %>
    <% for scope in scopes %>
    <%= link_to "#{scope} (#{@evaluation_scope_for_scope.send(scope).count})", evaluations_path(:scope => scope), :class => "btn btn-default #{((session[:scope][:evaluation].to_s == scope) ? 'active' : '')}" %>
    <% end %>
  </div>
</div>
<% end %>

<div class="row">
  <div class="col-md-12">
    <a class="btn btn-xs btn-default" id="hide-menu-btn">
      <i class="fa fa-caret-left"></i>
      <i class="fa fa-caret-left"></i>
    </a>
    <a class="btn btn-xs btn-default" id="show-menu-btn">
      <i class="fa fa-caret-right"></i>
      <i class="fa fa-caret-right"></i>
    </a>

    <a class="btn btn-xs btn-default pull-right" id="hide-search-btn">
      <i class="fa fa-caret-right"></i>
      <i class="fa fa-caret-right"></i>
    </a>
    <a class="btn btn-xs btn-default pull-right" id="show-search-btn">
      <i class="fa fa-caret-left"></i>
      <i class="fa fa-caret-left"></i>
    </a>
  </div>
</div>

<div class="row">
  <div class="col-md-9">
    <%= form_tag  batch_evaluations_path, :class => "form-inline" do %>

      <%= render :partial => "layouts/modal_columns", :locals => { :engine_name => '', :model_name => "evaluation", :model_columns => ['place_id','internet','food','drink','service','price','accomodation','noyse','general','created_at','updated_at'] } %>

      <table class="table table-striped table-bordered table-condensed">
        <thead>
          <tr>
            <th class="ac">
              <a class="" data-toggle="modal" href="#modal-columns" title="<%= t(:select_columns, :default => "Select Columns") %>" ><i class="fa fa-th-list"></i></a>
            </th>
            <th>
              <%= check_box_tag :checkall, '' %>
            </th>
            <th  class="bs-col-place" >
              <%= sorting_header("evaluation", "place_id", "") %>
            </th>
            <th <%= visible_column("evaluation", "internet") %> class="bs-col-internet">
              <%= sorting_header("evaluation", "internet", "") %>
            </th>
            <th <%= visible_column("evaluation", "food") %> class="bs-col-food">
              <%= sorting_header("evaluation", "food", "") %>
            </th>
            <th <%= visible_column("evaluation", "drink") %> class="bs-col-drink">
              <%= sorting_header("evaluation", "drink", "") %>
            </th>
            <th <%= visible_column("evaluation", "service") %> class="bs-col-service">
              <%= sorting_header("evaluation", "service", "") %>
            </th>
            <th <%= visible_column("evaluation", "price") %> class="bs-col-price">
              <%= sorting_header("evaluation", "price", "") %>
            </th>
            <th <%= visible_column("evaluation", "accomodation") %> class="bs-col-accomodation">
              <%= sorting_header("evaluation", "accomodation", "") %>
            </th>
            <th <%= visible_column("evaluation", "noyse") %> class="bs-col-noyse">
              <%= sorting_header("evaluation", "noyse", "") %>
            </th>
            <th <%= visible_column("evaluation", "general") %> class="bs-col-general">
              <%= sorting_header("evaluation", "general", "") %>
            </th>

            <!-- Beautiful_scaffold - AddField - Header - Do not remove -->
            <th <%= visible_column("evaluation", "created_at") %> class="bs-col-created_at">
              <%= sorting_header("evaluation", "created_at", "") %>
            </th>
            <th <%= visible_column("evaluation", "updated_at") %> class="bs-col-updated_at">
              <%= sorting_header("evaluation", "updated_at", "") %>
            </th>
            <th colspan="3">
              <label class="checkbox">
                <%= check_box_tag :checkallelt, 'all' %>
                <%= pluralize(@evaluation_scope.count, t('app.models.evaluation.bs_caption', :default => 'evaluation'), t('app.models.evaluation.bs_caption_plural', :default => 'evaluation')) %>
              </label>
            </th>
          </tr>
        </thead>
        <tbody>
          <% @evaluations.each do |evaluation| %>
          <tr class="line-<%= cycle("1","2") %>">
            <td class="ar"><%= evaluation.id %></td>
            <td><%= check_box_tag "ids[]",evaluation.id, false, :class => 'cbbatch' %></td>
            <td   class="bs-col-place <%= align_attribute("string") %>">
                <%= Place.find(evaluation.place_id).name %>
            </td>
            <td <%= visible_column("evaluation", "internet") %> class="bs-col-internet <%= align_attribute("integer") %>">
                <%= evaluation.internet %>
            </td>
            <td <%= visible_column("evaluation", "food") %> class="bs-col-food <%= align_attribute("string") %>">
                <%= evaluation.food %>
            </td>
            <td <%= visible_column("evaluation", "drink") %> class="bs-col-drink <%= align_attribute("string") %>">
                <%= evaluation.drink %>
            </td>
            <td <%= visible_column("evaluation", "service") %> class="bs-col-service <%= align_attribute("integer") %>">
                <%= evaluation.service %>
            </td>
            <td <%= visible_column("evaluation", "price") %> class="bs-col-price <%= align_attribute("integer") %>">
                <%= evaluation.price %>
            </td>
            <td <%= visible_column("evaluation", "accomodation") %> class="bs-col-accomodation <%= align_attribute("integer") %>">
                <%= evaluation.accomodation %>
            </td>
            <td <%= visible_column("evaluation", "noyse") %> class="bs-col-noyse <%= align_attribute("integer") %>">
                <%= evaluation.noyse %>
            </td>
            <td <%= visible_column("evaluation", "general") %> class="bs-col-general <%= align_attribute("integer") %>">
                <%= evaluation.general %>
            </td>
<!-- Beautiful_scaffold - AddField - Column - Do not remove -->
            <td <%= visible_column("evaluation", "created_at") %> class="bs-col-created_at <%= align_attribute("datetime") %>">
              <%= l(evaluation.created_at, :format => :long) %>
            </td>
            <td <%= visible_column("evaluation", "updated_at") %> class="bs-col-updated_at <%= align_attribute("datetime") %>">
              <%= l(evaluation.updated_at, :format => :long) %>
            </td>
            <td class="ac am"><%= link_to '<i class="fa fa-search"></i>'.html_safe, evaluation_path(evaluation), :title => t(:show, :default => "Show") %></td>
            <td class="ac am"><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_evaluation_path(evaluation), :title => t(:edit, :default => "Edit") %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <div class="btn-toolbar">
        <div class="btn-group">
          <% clean_params %>
          <%= will_paginate @evaluations,
                  :inner_window => 0,
                  :outer_window => 0,
                  :previous_label => t(:prev, :default => "Previous"),
                  :next_label => t(:next, :default => "Next") %>

        </div>
        <div class="btn-group pull-right">
          <%= link_to '<i class="fa fa-download"></i> CSV'.html_safe,  evaluations_path(:format => :csv), :class => "btn btn-default" %>
          <%= link_to '<i class="fa fa-download"></i> XML'.html_safe,  evaluations_path(:format => :xml), :class => "btn btn-default" %>
          <%= link_to '<i class="fa fa-download"></i> JSON'.html_safe, evaluations_path(:format => :json), :class => "btn btn-default" %>
          <%= link_to '<i class="fa fa-download"></i> PDF'.html_safe,  evaluations_path(:format => :pdf), :class => "btn btn-default" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/evaluations/new.html.erb
<h2><%= t(:new, :default => 'New') %> <%= t('app.models.evaluation.bs_caption', :default => 'evaluation') %></h2>

<h3> Rate from 1 to 5 starts the quality of  internet, service, price, accomodation, noyse and general evaluation. Describe the types of food and drink writing it down in their respective fields </h3>

<%= render 'form' %>

<%= link_to t(:back, :default => "Back"), evaluations_path, :class => "btn btn-default" %>

app/views/evaluations/show.html.erb
<h2><%= t(:show, :default => "Show") %> <%= t('app.models.evaluation.bs_caption', :default => 'evaluation') %></h2>

  <p>
    <b><%= t('app.models.evaluation.bs_attributes.internet', :default => 'internet') %>:</b>
      <%= @evaluation.internet %>
  </p>
  <p>
    <b><%= t('app.models.evaluation.bs_attributes.food', :default => 'food') %>:</b>
      <%= @evaluation.food %>
  </p>
  <p>
    <b><%= t('app.models.evaluation.bs_attributes.drink', :default => 'drink') %>:</b>
      <%= @evaluation.drink %>
  </p>
  <p>
    <b><%= t('app.models.evaluation.bs_attributes.service', :default => 'service') %>:</b>
      <%= @evaluation.service %>
  </p>
  <p>
    <b><%= t('app.models.evaluation.bs_attributes.price', :default => 'price') %>:</b>
      <%= @evaluation.price %>
  </p>
  <p>
    <b><%= t('app.models.evaluation.bs_attributes.accomodation', :default => 'accomodation') %>:</b>
      <%= @evaluation.accomodation %>
  </p>
  <p>
    <b><%= t('app.models.evaluation.bs_attributes.noyse', :default => 'noyse') %>:</b>
      <%= @evaluation.noyse %>
  </p>
  <p>
    <b><%= t('app.models.evaluation.bs_attributes.general', :default => 'general') %>:</b>
      <%= @evaluation.general %>
  </p>

<!-- Beautiful_scaffold - AddField - Field - Do not remove -->

<%= link_to t(:edit, :default => "Edit"), edit_evaluation_path(@evaluation), :class => "btn btn-default" %>
<%= link_to t(:back, :default => "Back"), evaluations_path, :class => "btn btn-default" %>