config/routes.rb
Rails.application.routes.draw do
  root :to => 'beautiful#dashboard'
  match ':model_sym/select_fields' => 'beautiful#select_fields', :via => [:get, :post]

  concern :bs_routes do
    collection do
      post :batch
      get  :treeview, :my_index
      match :search_and_filter, :action => :index, :as => :search, :via => [:get, :post]
    end
    member do
      post :treeview_update
    end
  end
  authenticate :user do
    resources :evaluations, only: [:new, :create, :edit, :update, :my_index]
    resources :places, only: [:new, :create, :edit, :update]
  end
  # Add route with concerns: :bs_routes here # Do not remove
  resources :places, concerns: :bs_routes
  
  resources :evaluations, concerns: :bs_routes
  

  resources :static_pages
  devise_for :users, :evaluations

  root to: "application#index"

  get '/about', to: 'static_pages#about'
#  get '/my_index', to: 'evaluations#my_index'
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  protect_from_forgery with: :exception

  def about
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_form.html.erb
<%= form_for(static_page) do |f| %>
  <% if static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
      <% static_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/static_pages/_form.html.haml
= form_for(static_page) do |f|
  - if static_page.errors.any?
    #error_explanation
      %h2
        = pluralize(static_page.errors.count, "error")
        prohibited this static_page from being saved:
      %ul
        - static_page.errors.full_messages.each do |message|
          %li= message
  .actions
    = f.submit

app/views/static_pages/about.html.erb
<h2>About</h2>
<p>This application is destinated to help home officers to find places with their own conditions' preference. </p>
<p>Developed by Vinicius Gesteira. 2017.</p>

<%= link_to t(:back, :default => "Back"), evaluations_path, :class => "btn btn-default" %>

app/views/static_pages/about.html.haml
%h1 Sobre
%p Tem wifi é um serviço desenvolvido para auxiliar pessoas que trabalham por conta própria a encontrarem locais mais apropriados para seu ofício, segundo recomendações feitas por outros
%p Desenvolvido por Vinicius Gesteira sem fins lucrativos. 2017.

app/views/static_pages/edit.html.erb
<h1>Editing Static Page</h1>

<%= render 'form', static_page: @static_page %>

<%= link_to 'Show', @static_page %> |
<%= link_to 'Back', static_pages_path %>

app/views/static_pages/edit.html.haml
%h1 Editing Static Page
= render 'form', static_page: @static_page
= link_to 'Show', @static_page
|
= link_to 'Back', static_pages_path

app/views/static_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Static Pages</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @static_pages.each do |static_page| %>
      <tr>
        <td><%= link_to 'Show', static_page %></td>
        <td><%= link_to 'Edit', edit_static_page_path(static_page) %></td>
        <td><%= link_to 'Destroy', static_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Static Page', new_static_page_path %>

app/views/static_pages/index.html.haml
%p#notice= notice
%h1 Static Pages
%table
  %thead
    %tr
      %th{:colspan => "3"}
  %tbody
    - @static_pages.each do |static_page|
      %tr
        %td= link_to 'Show', static_page
        %td= link_to 'Edit', edit_static_page_path(static_page)
        %td= link_to 'Destroy', static_page, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Static Page', new_static_page_path

app/views/static_pages/new.html.erb
<h1>New Static Page</h1>

<%= render 'form', static_page: @static_page %>

<%= link_to 'Back', static_pages_path %>

app/views/static_pages/new.html.haml
%h1 New Static Page
= render 'form', static_page: @static_page
= link_to 'Back', static_pages_path

app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>

app/views/static_pages/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_static_page_path(@static_page)
|
= link_to 'Back', static_pages_path