config/routes.rb
Rails.application.routes.draw do
  root :to => 'beautiful#dashboard'
  match ':model_sym/select_fields' => 'beautiful#select_fields', :via => [:get, :post]

  concern :bs_routes do
    collection do
      post :batch
      get  :treeview, :my_index
      match :search_and_filter, :action => :index, :as => :search, :via => [:get, :post]
    end
    member do
      post :treeview_update
    end
  end
  authenticate :user do
    resources :evaluations, only: [:new, :create, :edit, :update, :my_index]
    resources :places, only: [:new, :create, :edit, :update]
  end
  # Add route with concerns: :bs_routes here # Do not remove
  resources :places, concerns: :bs_routes
  
  resources :evaluations, concerns: :bs_routes
  

  resources :static_pages
  devise_for :users, :evaluations

  root to: "application#index"

  get '/about', to: 'static_pages#about'
#  get '/my_index', to: 'evaluations#my_index'
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :evaluations
  def self.inheritance_column
    'a'
  end

  validates :name, uniqueness: true

  include DefaultSortingConcern
  include FulltextConcern
  include CaptionConcern

  cattr_accessor :fulltext_fields do
    []
  end

  def self.permitted_attributes
    return :name,:address,:city,:state,:country,:type
  end
end

app/controllers/places_controller.rb
# encoding : utf-8


class PlacesController < BeautifulController

  before_action :load_place, :only => [:show, :edit, :update]

  # Uncomment for check abilities with CanCan
  #authorize_resource

  def index
    session['fields'] ||= {}
    session['fields']['place'] ||= (Place.columns.map(&:name) - ["id"])[0..4]
    do_select_fields('place')
    do_sort_and_paginate('place')
    
    @q = Place.ransack(
      params[:q]
    )

    @place_scope = @q.result(
      :distinct => true
    ).sorting(
      params[:sorting]
    )
    
    @place_scope_for_scope = @place_scope.dup
    
    unless params[:scope].blank?
      @place_scope = @place_scope.send(params[:scope])
    end
    
    @places = @place_scope.paginate(
      :page => params[:page],
      :per_page => 20
    ).to_a

    respond_to do |format|
      format.html{
        render
      }
      format.json{
        render :json => @place_scope.to_a
      }
      format.csv{
        require 'csv'
        csvstr = CSV.generate do |csv|
          csv << Place.attribute_names
          @place_scope.to_a.each{ |o|
            csv << Place.attribute_names.map{ |a| o[a] }
          }
        end 
        render :text => csvstr
      }
      format.xml{ 
        render :xml => @place_scope.to_a
      }             
      format.pdf{
        pdfcontent = PdfReport.new.to_pdf(Place,@place_scope)
        send_data pdfcontent
      }
    end
  end

  def show
    respond_to do |format|
      format.html{
        render
      }
      format.json { render :json => @place }
    end
  end

  def new
    @place = Place.new

    respond_to do |format|
      format.html{
        render
      }
      format.json { render :json => @place }
    end
  end

  def edit
    
  end

  def create
    @place = Place.new(params_for_model)

    respond_to do |format|
      if @place.save
        format.html {
          if params[:mass_inserting] then
            redirect_to places_path(:mass_inserting => true)
          else
            redirect_to place_path(@place), :flash => { :notice => t(:create_success, :model => "place") }
          end
        }
        format.json { render :json => @place, :status => :created, :location => @place }
      else
        format.html {
          if params[:mass_inserting] then
            redirect_to places_path(:mass_inserting => true), :flash => { :error => t(:error, "Error") }
          else
            render :action => "new"
          end
        }
        format.json { render :json => @place.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @place.update_attributes(params_for_model)
        format.html { redirect_to place_path(@place), :flash => { :notice => t(:update_success, :model => "place") }}
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @place.errors, :status => :unprocessable_entity }
      end
    end
  end

# def destroy
#   @place.destroy

#   respond_to do |format|
#     format.html { redirect_to places_url }
#     format.json { head :ok }
#   end
# end

  def batch
    attr_or_method, value = params[:actionprocess].split(".")

    @places = []    
    
    Place.transaction do
      if params[:checkallelt] == "all" then
        # Selected with filter and search
        do_sort_and_paginate(:place)

        @places = Place.ransack(
          params[:q]
        ).result(
          :distinct => true
        )
      else
        # Selected elements
        @places = Place.find(params[:ids].to_a)
      end

      @places.each{ |place|
        if not Place.columns_hash[attr_or_method].nil? and
               Place.columns_hash[attr_or_method].type == :boolean then
         place.update_attribute(attr_or_method, boolean(value))
         place.save
        else
          case attr_or_method
          # Set here your own batch processing
          # place.save
          when "destroy" then
            place.destroy
          end
        end
      }
    end
    
    redirect_to :back
  end

  def treeview

  end

  def treeview_update
    modelclass = Place
    foreignkey = :place_id

    render :nothing => true, :status => (update_treeview(modelclass, foreignkey) ? 200 : 500)
  end
  
  private 
  
  def load_place
    @place = Place.find(params[:id])
  end

  def params_for_model
    params.require(:place).permit(Place.permitted_attributes)
  end
end

app/helpers/places_helper.rb
# encoding : utf-8
require "beautiful_helper"


module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
        <% @place.errors.full_messages.each do |msg| %><li><%= msg %></li><% end %>
      </ul>
    </div>
  <% end %>
      <div class="form-group">
      <%= f.label :name, t('app.models.place.bs_attributes.name', :default => 'name').capitalize, :class => "control-label" %>
      <%= f.text_field :name, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :address, t('app.models.place.bs_attributes.address', :default => 'address').capitalize, :class => "control-label" %>
      <%= f.text_field :address, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :city, t('app.models.place.bs_attributes.city', :default => 'city').capitalize, :class => "control-label" %>
      <%= f.text_field :city, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :state, t('app.models.place.bs_attributes.state', :default => 'state').capitalize, :class => "control-label" %>
      <%= f.text_field :state, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :country, t('app.models.place.bs_attributes.country', :default => 'country').capitalize, :class => "control-label" %>
      <%= f.text_field :country, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :type, t('app.models.place.bs_attributes.type', :default => 'type').capitalize, :class => "control-label" %>
      <%= f.text_field :type, :class => "form-control" %>
    </div>
<!-- Beautiful_scaffold - AddField - Do not remove -->
  <div>
    <%= f.submit :class => "btn btn-primary", :data => { :disable_with => t(:saving, :default => "Saving...") } %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h2><%= t(:editing, :default => 'Editing') %> <%= t('app.models.place.bs_caption', :default => 'place') %></h2>

<%= render 'form' %>

<%= link_to t(:back, :default => "Back"), places_path, :class => "btn btn-default" %>

app/views/places/index.html.erb
<h2><%= t(:listing, :default => "Listing") %> <%= t('app.models.place.bs_caption_plural', :default => 'place') %></h2>

<p>
  <%= link_to '<i class="fa fa-plus"></i> '.html_safe + t(:new, :default => "New") + ' ' + t('app.models.place.bs_caption', :default => 'place'), new_place_path, :class => "btn btn-default" %>
  <% if Place.columns.map(&:name).include?("place_id") then %>
    <%= link_to '<i class="fa fa-folder-close"></i> '.html_safe + t(:treeview, :default => "Treeview") + ' ' + t('app.models.place.bs_caption', :default => 'place'), treeview_places_path, :class => "btn btn-default" %>
  <% end %>
</p>


<%# Set your scopes below (string in array) %>
<% scopes = [] %>
<% if not scopes.blank? then %>
<div class="btn-toolbar">
  <div class="btn-group">
    <%= link_to "All (#{@place_scope_for_scope.count})", places_path(:scope => ""), :class => "btn btn-default #{((session[:scope][:place].to_s == '') ? 'active' : '')}" %>
    <% for scope in scopes %>
    <%= link_to "#{scope} (#{@place_scope_for_scope.send(scope).count})", places_path(:scope => scope), :class => "btn btn-default #{((session[:scope][:place].to_s == scope) ? 'active' : '')}" %>
    <% end %>
  </div>
</div>
<% end %>

<div class="row">
  <div class="col-md-12">
    <a class="btn btn-xs btn-default" id="hide-menu-btn">
      <i class="fa fa-caret-left"></i>
      <i class="fa fa-caret-left"></i>
    </a>
    <a class="btn btn-xs btn-default" id="show-menu-btn">
      <i class="fa fa-caret-right"></i>
      <i class="fa fa-caret-right"></i>
    </a>

    <a class="btn btn-xs btn-default pull-right" id="hide-search-btn">
      <i class="fa fa-caret-right"></i>
      <i class="fa fa-caret-right"></i>
    </a>
    <a class="btn btn-xs btn-default pull-right" id="show-search-btn">
      <i class="fa fa-caret-left"></i>
      <i class="fa fa-caret-left"></i>
    </a>
  </div>
</div>

<div class="row">
  <div class="col-md-9">
    <%= form_tag  batch_places_path, :class => "form-inline" do %>

      <%= render :partial => "layouts/modal_columns", :locals => { :engine_name => '', :model_name => "place", :model_columns => ['name','address','city','state','country','type','created_at','updated_at'] } %>

      <table class="table table-striped table-bordered table-condensed">
        <thead>
          <tr>
            <th class="ac">
              <a class="" data-toggle="modal" href="#modal-columns" title="<%= t(:select_columns, :default => "Select Columns") %>" ><i class="fa fa-th-list"></i></a>
            </th>
            <th>
              <%= check_box_tag :checkall, '' %>
            </th>
            <th <%= visible_column("place", "name") %> class="bs-col-name">
              <%= sorting_header("place", "name", "") %>
            </th>
            <th <%= visible_column("place", "address") %> class="bs-col-address">
              <%= sorting_header("place", "address", "") %>
            </th>
            <th <%= visible_column("place", "city") %> class="bs-col-city">
              <%= sorting_header("place", "city", "") %>
            </th>
            <th <%= visible_column("place", "state") %> class="bs-col-state">
              <%= sorting_header("place", "state", "") %>
            </th>
            <th <%= visible_column("place", "country") %> class="bs-col-country">
              <%= sorting_header("place", "country", "") %>
            </th>
            <th <%= visible_column("place", "type") %> class="bs-col-type">
              <%= sorting_header("place", "type", "") %>
            </th>

            <!-- Beautiful_scaffold - AddField - Header - Do not remove -->
            <th <%= visible_column("place", "created_at") %> class="bs-col-created_at">
              <%= sorting_header("place", "created_at", "") %>
            </th>
            <th <%= visible_column("place", "updated_at") %> class="bs-col-updated_at">
              <%= sorting_header("place", "updated_at", "") %>
            </th>
            <th colspan="3">
              <label class="checkbox">
                <%= check_box_tag :checkallelt, 'all' %>
                <%= pluralize(@place_scope.count, t('app.models.place.bs_caption', :default => 'place'), t('app.models.place.bs_caption_plural', :default => 'place')) %>
              </label>
            </th>
          </tr>
        </thead>
        <tbody>
          <% @places.each do |place| %>
          <tr class="line-<%= cycle("1","2") %>">
            <td class="ar"><%= place.id %></td>
            <td><%= check_box_tag "ids[]",place.id, false, :class => 'cbbatch' %></td>
            <td <%= visible_column("place", "name") %> class="bs-col-name <%= align_attribute("string") %>">
                <%= place.name %>
            </td>
            <td <%= visible_column("place", "address") %> class="bs-col-address <%= align_attribute("string") %>">
                <%= place.address %>
            </td>
            <td <%= visible_column("place", "city") %> class="bs-col-city <%= align_attribute("string") %>">
                <%= place.city %>
            </td>
            <td <%= visible_column("place", "state") %> class="bs-col-state <%= align_attribute("string") %>">
                <%= place.state %>
            </td>
            <td <%= visible_column("place", "country") %> class="bs-col-country <%= align_attribute("string") %>">
                <%= place.country %>
            </td>
            <td <%= visible_column("place", "type") %> class="bs-col-type <%= align_attribute("string") %>">
                <%= place.type %>
            </td>
<!-- Beautiful_scaffold - AddField - Column - Do not remove -->
            <td <%= visible_column("place", "created_at") %> class="bs-col-created_at <%= align_attribute("datetime") %>">
              <%= l(place.created_at, :format => :long) %>
            </td>
            <td <%= visible_column("place", "updated_at") %> class="bs-col-updated_at <%= align_attribute("datetime") %>">
              <%= l(place.updated_at, :format => :long) %>
            </td>
            <td class="ac am"><%= link_to '<i class="fa fa-search"></i>'.html_safe, place_path(place), :title => t(:show, :default => "Show") %></td>
            <td class="ac am"><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_place_path(place), :title => t(:edit, :default => "Edit") %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <div class="btn-toolbar">
        <div class="btn-group">
          <% clean_params %>
          <%= will_paginate @places,
                  :inner_window => 0,
                  :outer_window => 0,
                  :previous_label => t(:prev, :default => "Previous"),
                  :next_label => t(:next, :default => "Next") %>

        </div>
        <div class="btn-group pull-right">
          <%= link_to '<i class="fa fa-download"></i> CSV'.html_safe,  places_path(:format => :csv), :class => "btn btn-default" %>
          <%= link_to '<i class="fa fa-download"></i> XML'.html_safe,  places_path(:format => :xml), :class => "btn btn-default" %>
          <%= link_to '<i class="fa fa-download"></i> JSON'.html_safe, places_path(:format => :json), :class => "btn btn-default" %>
          <%= link_to '<i class="fa fa-download"></i> PDF'.html_safe,  places_path(:format => :pdf), :class => "btn btn-default" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-3">
    <%= search_form_for @q, :url => search_places_path, :html => { :class => "well well-small search-and-filter" }, :method => :post do |f| %>

      <h3><%= t("search_and_filter", :default => "Search & filter") %></h3>

      <%= ransack_field("place", "name", f, "Name") %>
      <%= ransack_field("place", "address", f, "Address") %>
      <%= ransack_field("place", "city", f, "City") %>
      <%= ransack_field("place", "state", f, "State") %>
      <%= ransack_field("place", "country", f, "Country") %>
      <%= ransack_field("place", "type", f, "Type") %>


      <!-- Beautiful_scaffold - AddField - Search - Do not remove -->

      <div class="panel-group">
        <div class="panel panel-default">
          <div class="panel-heading">
          </div>


      <%= f.submit t(:filter, :default => "Filter"), :class => "btn btn-primary" %>
      <%= link_to  t(:cancel, :default => "Cancel"), places_path(:nosearch => "ok"), :class => "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/places/new.html.erb
<h2><%= t(:new, :default => 'New') %> <%= t('app.models.place.bs_caption', :default => 'place') %></h2>

<%= render 'form' %>

<%= link_to t(:back, :default => "Back"), places_path, :class => "btn btn-default" %>

app/views/places/show.html.erb
<h2><%= t(:show, :default => "Show") %> <%= t('app.models.place.bs_caption', :default => 'place') %></h2>

  <p>
    <b><%= t('app.models.place.bs_attributes.name', :default => 'name') %>:</b>
      <%= @place.name %>
  </p>
  <p>
    <b><%= t('app.models.place.bs_attributes.address', :default => 'address') %>:</b>
      <%= @place.address %>
  </p>
  <p>
    <b><%= t('app.models.place.bs_attributes.city', :default => 'city') %>:</b>
      <%= @place.city %>
  </p>
  <p>
    <b><%= t('app.models.place.bs_attributes.state', :default => 'state') %>:</b>
      <%= @place.state %>
  </p>
  <p>
    <b><%= t('app.models.place.bs_attributes.country', :default => 'country') %>:</b>
      <%= @place.country %>
  </p>
  <p>
    <b><%= t('app.models.place.bs_attributes.type', :default => 'type') %>:</b>
      <%= @place.type %>
  </p>

<!-- Beautiful_scaffold - AddField - Field - Do not remove -->

<%= link_to t(:edit, :default => "Edit"), edit_place_path(@place), :class => "btn btn-default" %>
<%= link_to t(:back, :default => "Back"), places_path, :class => "btn btn-default" %>

app/views/places/treeview.html.erb
<h2><%= t(:treeview, :default => 'Treeview') %> <%= t('app.models.place.bs_caption', :default => 'place') %></h2>

<%
namespace_for_url = ""
plural_model_name = "places"
model_name        = "place"
opened_node       = Place.select(:id).all.map{ |g| "'treeelt_" + g.id.to_s + "'" }.join(',').html_safe
%>

<div id="treeview" data-model="<%= model_name %>" data-url="/<%= namespace_for_url %><%= plural_model_name %>/" data-opened="[<%= opened_node %>]">
  <ul>
    <% Place.transaction do %>
    <% ar = Place.where(:place_id => nil) %>
    <% ar = ar.order("position") if Place.column_names.include?("position") %>
      <% for g in ar.all %>
        <%= build_treeview(g, 'places') %>
      <% end %>
    <% end %>
  </ul>
</div>