config/routes.rb
Rails.application.routes.draw do
  root :to => 'beautiful#dashboard'
  match ':model_sym/select_fields' => 'beautiful#select_fields', :via => [:get, :post]

  concern :bs_routes do
    collection do
      post :batch
      get  :treeview, :my_index
      match :search_and_filter, :action => :index, :as => :search, :via => [:get, :post]
    end
    member do
      post :treeview_update
    end
  end
  authenticate :user do
    resources :evaluations, only: [:new, :create, :edit, :update, :my_index]
    resources :places, only: [:new, :create, :edit, :update]
  end
  # Add route with concerns: :bs_routes here # Do not remove
  resources :places, concerns: :bs_routes
  
  resources :evaluations, concerns: :bs_routes
  

  resources :static_pages
  devise_for :users, :evaluations

  root to: "application#index"

  get '/about', to: 'static_pages#about'
#  get '/my_index', to: 'evaluations#my_index'
end

app/views/layouts/_beautiful_menu.html.erb
<!-- Beautiful Scaffold Menu Do Not Touch This -->
      <li class="<%= "active" if params[:controller] == "places" %>">
        <%= link_to t('app.models.place.bs_caption_plural', :default => 'place').capitalize, places_path %>
      </li>
      <li class="<%= "active" if params[:controller] == "evaluations" %>">
        <%= link_to t('app.models.evaluation.bs_caption_plural', :default => 'evaluation').capitalize, evaluations_path %>
      </li>
<% if user_signed_in? %>
  <li><%= link_to 'My Evaluations', my_index_evaluations_path %></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Log in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
  <li><%= link_to 'About', '/about' %></li>

app/views/layouts/_form_habtm_tag.html.erb
<%#=
  render :partial => "layouts/form_habtm_tag", :locals => {
    :model_class => @product,
    :model_name => "product",
    :plural_model_name => "products",
    :linked_model_name => "tag",
    :plural_linked_model_name => "tags",
    :namespace_bs => "admin",
    :field_to_search_for_linked_model => "name",
    :f => f
  }
  # Example to put in a _form.html.erb
%>
<% path_namespace = '/' + namespace_bs if not namespace_bs.blank? %>

<div class="form-group">
    <%= f.label plural_linked_model_name.to_sym, t(plural_linked_model_name.to_sym, :default => plural_linked_model_name.capitalize), :class => "control-label" %>
    <div>
        <ul class="bs-tagit" id="<%= model_name %>_<%= linked_model_name %>_ids" name="<%= model_name %>[<%= linked_model_name %>_ids][]" data-url="<%= path_namespace %>/<%= plural_linked_model_name %>/search_and_filter.json" data-param="q[<%= field_to_search_for_linked_model %>_cont]" data-result="caption">
          <% begin %>
            <% for elt in model_class.send(plural_linked_model_name) %>
            <li data-value="<%= elt.id %>"><%= elt.caption %></li>
            <% end %>
          <% rescue %>
          <% end %>
        </ul>
    </div>
</div>

app/views/layouts/_mass_inserting.html.erb
<% model = ("#{(engine.blank? ? '' : "#{engine.camelize}::")}#{model_name.camelize}").constantize %>
<% formparams = [] %>
<% if not namespace.blank? then %>
  <% formparams << namespace %>
<% end %>
<% formparams << model.new %>
<%= form_for formparams, :method => :post, :html => { :class => "well well-small form-inline mass-inserting #{(params[:mass_inserting] ? 'setfocus' : '')}" } do |f| %>
  <%= hidden_field_tag :mass_inserting, true %>
  <% for col in model_columns %>
    <div <%= visible_column(model_name, col, 'inline') %> class="col-<%= col %>">
      <%=
        ar = model.columns_hash[col]
        if not ar.nil? then
          case ar.type
          when :integer then
            if col =~ /.*_id/ then
              f.collection_select((col).to_sym, col.camelize.constantize.all, :id, :caption, { :include_blank => true, :selected => (begin params[:q][col + "_eq"].to_i rescue '' end) }, {:class => "form-control"})
            else
              f.text_field(col.to_sym, :placeholder => t(i18n_translate_path(model_name, col)).capitalize, :class => "form-control")
            end
          when :boolean then
            (
            "<label class='bs-label-ib'>#{f.check_box(col.to_sym, {}, true, false)}#{t(i18n_translate_path(model_name, col)).capitalize}</label>".html_safe
            )
          else
            f.text_field(col.to_sym, :placeholder => t(i18n_translate_path(model_name, col)).capitalize, :class => "form-control")
          end
        else
          f.collection_select((col + '_id').to_sym, col.camelize.constantize.all, :id, :caption, { :include_blank => true, :selected => (begin params[:q][col + "_id_eq"].to_i rescue '' end) }, {:class => "form-control"})
        end
      %>
    </div>
  <% end %>
  <div style="display:inline;">
    <%= f.submit t(:create, :default => "Create"), :class => "btn btn-default", :data => { :disable_with => t(:saving, :default => "Saving...") } %>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_modal_columns.html.erb
<div class="modal fade" id="modal-columns">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3><%= t(:select_columns, :default => "Select Columns") %></h3>
      </div>
      <div class="modal-body">
        <% for field in model_columns %>
          <label class="checkbox">
            <input type="checkbox" name="field[]" value="<%= field %>" <%= "checked" if session['fields'][model_name.to_s].include?(field) %>> <%= t("app.models.#{model_name}.bs_attributes.#{field}", :default => field.capitalize) %>
          </label><br />
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="filter-columns" data-url="/<%= engine_name %><%= model_name %>/select_fields">Ok</button>
        <button type="button" class="btn btn-default" id="cancel-filter-columns"><%= t(:cancel, :default => "Cancel") %></button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_nav_links_for_auth.html.haml
- if user_signed_in?
  %li= link_to 'Edit account', edit_user_registration_path
  %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  %li= link_to 'Sign in', new_user_session_path
  %li= link_to 'Sign up', new_user_registration_path

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'TEM WIFI?', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      = link_to 'TEM WIFI?', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/nav_links_for_auth'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tem wifi?</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Tem wifi?
    = stylesheet_link_tag 'registrant-manifest', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'registrant-manifest', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/layouts/beautiful_layout.html.erb
<!DOCTYPE html>
<html lang="<%= (I18n.default_locale) %>">
  <head>
    <meta charset="utf-8">
    <title>Temwifi?</title>

    <meta name="description" content="Temwifi?">
    <meta name="author" content="Vinicius Lins Gesteira">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag "application-bs" %>
    <%= javascript_include_tag "application-bs" %>

    <%= csrf_meta_tags %>
    <%= yield :head %>
  </head>
  <body style="display:none;">
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <i class="fa fa-bars"></i>
          </button>
          <a class="navbar-brand" href="#">
            Temwifi?
          </a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <%= render :partial => "layouts/beautiful_menu" %>
          </ul>
          <ul class="nav navbar-nav pull-right">
            <li>
              <!-- Beautiful_scaffold - Signin - Do not remove -->
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2">
          <ul class="nav nav-pills nav-stacked">
            <%= render :partial => "layouts/beautiful_menu" %>
          </ul>
        </div>
        <div class="col-md-10">
          <% if not flash[:notice].blank? then %>
            <div class="alert alert-info">
              <a class="close" data-dismiss="alert" href="#">×</a>
              <h4 class="alert-heading">Info : </h4>
              <%= flash[:notice] %>
            </div>
          <% end %>
          <% if not flash[:error].blank? then %>
            <div class="alert alert-danger">
              <a class="close" data-dismiss="alert" href="#">×</a>
              <h4 class="alert-heading">Error : </h4>
              <%= flash[:error] %>
            </div>
          <% end %>
          <div>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>

    <div class="loader" style="display:none">
      <div class="circle"></div>
      <div class="circle1"></div>
    </div>

    <!-- Beautiful_scaffold - Modal - Do not remove -->

    <script type="text/javascript">
      <% if not @opened_modal.blank? then %>
      $('<%= @opened_modal %>').modal('show');
      <% end %>
    </script>
    <footer>
      <p>This site is best viewed on Firefox.</p>
      <p>Vinicius Gesteira. 2017.</p>
    </footer>
  </body>
</html>